parameters:
#    andrejczyn_hellow_world.example.class: Andrejczyn\Bundle\HellowWorldBundle\Example

services:
#    andrejczyn_hellow_world.example:
#        class: %andrejczyn_hellow_world.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
